name: TestJava

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile Java classes and tests
        run: |
          javac -cp "testresources/junit-platform-console-standalone-1.6.0.jar" \
            src/com/mycompany/st10473692_formative1_part2/*.java \
            test/com/mycompany/st10473692_formative1_part2/*.java

      - name: Run all tests
        run: |
          java -jar testresources/junit-platform-console-standalone-1.6.0.jar \
            -cp src:test -scan-class-path
