name: TestJava

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List project structure
        run: |
          echo "=== Source Structure ==="
          find src || true
          echo "=== testresources Structure ==="
          find testresources || true

      - name: Compile source and test classes
        run: |
          mkdir -p build/classes
          javac -cp testresources/junit-platform-console-standalone-1.6.0.jar \
            -d build/classes \
            src/main/java/com/mycompany/st10473692_formative1_part2/*.java \
            src/test/java/com/mycompany/st10473692_formative1_part2/*.java

      - name: Run all unit tests
        run: |
          java -jar testresources/junit-platform-console-standalone-1.6.0.jar \
            -cp build/classes \
            --scan-classpath
