name: TestJava

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - list directory structure
        run: |
          echo "==== src/main/java ===="
          find src/main/java
          echo "==== src/test/java ===="
          find src/test/java

      - name: Compile Java source and test files
        run: |
          mkdir -p testresources/classes
          javac -cp "testresources/junit-platform-console-standalone-1.6.0.jar" \
            -d testresources/classes \
            src/main/java/com/mycompany/st10473692_formative1_part2/*.java \
            src/test/java/com/mycompany/st10473692_formative1_part2/*.java

      - name: Run UserTest
        run: |
          java -jar testresources/junit-platform-console-standalone-1.6.0.jar \
            -cp testresources/classes \
            --select-class com.mycompany.st10473692_formative1_part2.UserTest

      - name: Run MessageTest
        run: |
          java -jar testresources/junit-platform-console-standalone-1.6.0.jar \
            -cp testresources/classes \
            --select-class com.mycompany.st10473692_formative1_part2.MessageTest

      - name: Run LoginTest
        run: |
          java -jar testresources/junit-platform-console-standalone-1.6.0.jar \
            -cp testresources/classes \
            --select-class com.mycompany.st10473692_formative1_part2.LoginTest
